config/routes.rb
Rails.application.routes.draw do
  resources:locations
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :location
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :user
  has_many_attached :photos
end

app/models/partnership.rb
class Partnership < ApplicationRecord
  belongs_to :user
  belongs_to :location
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_event.rb
class UserEvent < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def show
    @location = Location.find(params[:id])
  end

  def new
    @location = Location.create
  end

  def update
  end

  def delete
  end

  def index
    @locations = Location.all
  end

  def create
    @location = Location.new(location_params)
    @location.user = current_user
    @location.save
    if @location.save
      redirect_to location_path(@location)
    else
      render :new
    end
  end

  private

  def location_params
    params.require(:location).permit(:name, :photos, :postcode, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @locations = Location.all.first(3)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DigShareGrow</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@300;400&display=swap" rel="stylesheet">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>


      <%= yield %>

  </body>
</html>

app/views/locations/delete.html.erb
<h1>Locations#delete</h1>
<p>Find me in app/views/locations/delete.html.erb</p>

app/views/locations/index.html.erb
<% @locations.each do |location| %>
<%= link_to location_path(location) do %>
  <div class="p-1 card d-flex flex-column justify-content-end" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path location.photos.first.key, height: 300, width: 400, crop: :fill %>'); height: 300px; width: 400px">
    <div class="card-info"><h2><%= location.name %></h2></div>
  </div>
  <% end %>
<% end %>

app/views/locations/new.html.erb
<h1>Locations#new</h1>
<%= simple_form_for @location do |f| %>
  <%= f.input :name %>
  <%= f.input :postcode %>
  <%= f.input :description, as: :text %>
  <%= f.input :photos, as: :file %>
  <%= f.button :submit %>
<% end %>

app/views/locations/show.html.erb
<h1><%= @location.name %></h1>
<h4><i class="fas fa-user-circle"></i> <%= @location.user.username %></h4>
<% if @location.photos.attached? %>
  <%= cl_image_tag @location.photos.first.key, height: 300, width: 400, crop: :fill %>
<% else %>
  <%= image_tag 'placeholder_generic.png', height: 300, width: 400, crop: :fill %>
<% end %>
<p><%= @location.description %></p>

<%= link_to locations_path do %>
  <button type="button" class="btn btn-outline-light">Back</button>
<% end %>

app/views/locations/update.html.erb
<h1>Locations#update</h1>
<p>Find me in app/views/locations/update.html.erb</p>

app/views/pages/home.html.erb
<div class="main-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path 'carrots.jpg', crop: :cover %>);">
  <h1>Join the social growing community</h1>
  <%= link_to locations_path do %>
    <button type="button" class="btn btn-outline-light m-5">Find out more</button>
  <% end %>
</div>

<div class="container">
  <div class="article-block d-flex my-2">
    <div>
      <%= image_tag('tomatoes.jpg', size: "400x300" ) %>
    </div>
    <div class="d-flex align-items-center">
      <div>
        <h3 class="m-1">At DigShareGrow, you'll find a friendly community of expert and novice growers willing to share their time and experience to help you learn new skills, get more from your allotment or simply enjoy growing fresh produce.</h3>
          <%= link_to locations_path do %>
            <button type="button" class="btn btn-outline-light m-1 mt-5">How it works</button>
          <% end %>
      </div>
    </div>
  </div>

  <div class="article-block my-5 text-center">
    <h1>View nearby opportunities</h1>
    <div class="d-flex flex-wrap justify-content-between mt-5">
      <% @locations.each do |location| %>
        <%= link_to location_path(location) do %>
          <div class="p-1 m-1 card d-flex flex-column justify-content-end" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path location.photos.first.key, height: 250, width: 300, crop: :fill %>'); height: 250px; width: 300px">
            <div class="card-info"><h2><%= location.name %></h2></div>
          </div>
        <% end %>
      <% end %>
    </div>
    <%= link_to locations_path do %>
      <button type="button" class="btn btn-outline-light m-1 mt-5">View all allotments</button>
    <% end %>
  </div>
</div>
<div class="blue-canvas">
  <div class="container">
    <div class="text-center pt-5 pb-2">
      <h1>Need another pair of hands?</h1>
    </div>
    <div class="article-block d-flex my-2">
      <div class="d-flex align-items-center">
        <div>
        <h3 class="m-1"></h3>
          <%= link_to locations_path do %>
            <button type="button" class="btn btn-outline-light m-1 mt-5">How it works</button>
          <% end %>
      </div>
      </div>
      <div>
        <%= image_tag('vegbox.jpg', size: "400x300" ) %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <h3>DigShareGrow</h3>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "New Location", new_location_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "See all Locations", locations_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>